<?php
/**
 * @var $block \PeterBrain\ModalOverlay\Block\ModalOverlay
 */
?>
<?php if ($block->isEnabled()): ?>
    <?php if ($content = $block->getContent('modal-overlay_popup')): ?>

        <div id="modal-overlay" style="display: none;">
            <?= /* @noEscape */ $content; ?>
        </div>

        <script type="text/x-magento-init">
        {
            "*": {
                "PeterBrain_ModalOverlay/js/modal_overlay": {
                    "visited_pages_threshold": <?= (int) $block->getVisitedPagesThreshold(); ?>
                }
            }
        }
        </script>

    <?php endif; ?>
<?php endif; ?>
