<?php $helper = $this->helper('PeterBrain\ModalOverlay\Helper\Data'); ?>

<?php if ($helper->isEnabled()): ?>
  <?php if ($content = $block->getContent('modal-overlay_popup')): ?>

    <div id="modal-overlay" style="display: none;">
      <?php echo $content; ?>
    </div>

    <script type="text/x-magento-init">
    {
      "*": {
        "PeterBrain_ModalOverlay/js/modal_overlay": {
          "visited_pages_threshold": <?php echo $helper->getVisitedPagesThreshold(); ?>
        }
      }
    }
    </script>

  <?php endif; ?>
<?php endif; ?>
