<?php $helper = $this->helper('PeterBrain\ModalOverlay\Helper\Data'); ?>

<?php if ($helper->isEnabled()): ?>
  <?php if ($content = $block->getContent('modal-overlay_popup')): ?>

    <div id="modal-overlay" style="display: none;">
      <?php echo $content; ?>
    </div>

    <script type="text/x-magento-init">
    {
      "*": {
        "Magento_Ui/js/core/app": {
          "components": {
            "modal_overlay": {
              "component": "PeterBrain_ModalOverlay/js/modal_overlay"
            }
          }
        }
      }
    }
    </script>

  <?php endif; ?>
<?php endif; ?>
